name: Rust Format Check

on:
  push:
    branches: [ main ]
    paths:
      - '**.rs'
  pull_request:
    branches: [ main ]
    paths:
      - '**.rs'

jobs:
  format:
    name: Check Rust Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          
      - name: Check formatting
        run: cargo fmt -- --check 